'use client';

import { useState, useEffect } from 'react';
import { Event, EventFormProps } from '@/types';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/Select';

export default function EventForm({ initialData, onSubmit, onCancel, isUpdateForm }: EventFormProps) {
  const [formData, setFormData] = useState<Partial<Event>>({
    title: '',
    description: '',
    date: '',
    eventLink: '',
    status: 'pending',
    targetAudience: 'both',
  });

  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
    } else {
      setFormData({
        title: '',
        description: '',
        date: '',
        status: 'pending' ,
        targetAudience: 'both',
      });
    }
  }, [initialData]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement> | { target: { name: string; value: string } }
  ) => {
    const { name, value } = 'target' in e ? e.target : e;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      // Ensure all required fields are present
      const eventData: Event = {
        id: initialData?.id || '', // ID will be generated by backend for new events
        title: formData.title || '',
        description: formData.description || '',
        date: formData.date || '',
        eventLink: formData.eventLink || '',
        status: formData.status || 'pending',
        targetAudience: formData.targetAudience || 'both',
      };
      await onSubmit(eventData);
    } catch (error) {
      console.error('Error submitting form:', error);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="mb-8 p-6 bg-white/10 rounded-lg border border-white/20">
      <div className="grid gap-4">
        <div>
          <label htmlFor="title" className="block text-sm font-medium text-gray-300">
            Title
          </label>
          <Input
            id="title"
            name="title"
            value={formData.title}
            onChange={handleChange}
            className="mt-1 bg-white/5 text-white border-white/20"
            required
          />
        </div>
        <div>
          <label htmlFor="description" className="block text-sm font-medium text-gray-300">
            Description
          </label>
          <Textarea
            id="description"
            name="description"
            value={formData.description}
            onChange={handleChange}
            className="mt-1 bg-white/5 text-white border-white/20"
            rows={4}
            required
          />
        </div>
        <div>
          <label htmlFor="date" className="block text-sm font-medium text-gray-300">
            Date
          </label>
          <Input
            id="date"
            name="date"
            type="datetime-local"
            value={formData.date}
            onChange={handleChange}
            className="mt-1 bg-white/5 text-white border-white/20"
            required
          />
        </div>

                <div>
          <label htmlFor="date" className="block text-sm font-medium text-gray-300">
            Event Link
          </label>
          <Input
            id="eventLink"
            name="eventLink"
            value={formData.eventLink}
            onChange={handleChange}
            className="mt-1 bg-white/5 text-white border-white/20"
            required
          />
        </div>
        <div>
          <label htmlFor="status" className="block text-sm font-medium text-gray-300">
            Status
          </label>
          <Select
            name="status"
            value={formData.status}
            onValueChange={(value) => handleChange({ target: { name: 'status', value } })}
          >
            <SelectTrigger className="mt-1 bg-white/5 border-white/20 text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pending">pending</SelectItem>
              <SelectItem value="approved">approved</SelectItem>
              <SelectItem value="cancelled">cancelled</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label htmlFor="targetAudience" className="block text-sm font-medium text-gray-300">
            Target Audience
          </label>
          <Select
            name="targetAudience"
            value={formData.targetAudience}
            onValueChange={(value) => handleChange({ target: { name: 'targetAudience', value } })}
          >
            <SelectTrigger className="mt-1 bg-white/5 border-white/20 text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="students">Students</SelectItem>
              <SelectItem value="alumni">Alumni</SelectItem>
              <SelectItem value="both">Both</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="mt-6 flex gap-4">
        <Button type="submit" className="bg-white/20 hover:bg-white/30 text-white">
          {isUpdateForm ? 'Update Event' : 'Add Event'}
        </Button>
        <Button type="button" onClick={onCancel} className="bg-gray-500 hover:bg-gray-600 text-white">
          Cancel
        </Button>
      </div>
    </form>
  );
}